# coding: utf-8

"""
    Paragon Insights APIs

    API interface for PI application  # noqa: E501

    OpenAPI spec version: 4.0.0
    Contact: healthbot-feedback@juniper.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.utility_api import UtilityApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUtilityApi(unittest.TestCase):
    """UtilityApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.utility_api.UtilityApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_junosdecode(self):
        """Test case for junosdecode

        Decode string with Junos  # noqa: E501
        """
        pass

    def test_junosencode(self):
        """Test case for junosencode

        Encode string with Junos  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
