# coding: utf-8

"""
    Paragon Insights APIs

    API interface for PI application  # noqa: E501

    OpenAPI spec version: 4.0.0
    Contact: healthbot-feedback@juniper.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.rule_schema_ruleproperties_isscalingrule import RuleSchemaRulepropertiesIsscalingrule  # noqa: E501
from swagger_client.rest import ApiException


class TestRuleSchemaRulepropertiesIsscalingrule(unittest.TestCase):
    """RuleSchemaRulepropertiesIsscalingrule unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRuleSchemaRulepropertiesIsscalingrule(self):
        """Test RuleSchemaRulepropertiesIsscalingrule"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.rule_schema_ruleproperties_isscalingrule.RuleSchemaRulepropertiesIsscalingrule()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
