{# Copyright (c) 2022, Juniper Networks, Inc.
# All rights reserved.
}
# coding: utf-8

"""
    Paragon Insights APIs

    API interface for PI application  # noqa: E501

    OpenAPI spec version: 4.0.0
    Contact: healthbot-feedback@juniper.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.devicegroup_schema_paragonactiveassurance import DevicegroupSchemaParagonactiveassurance  # noqa: E501
from swagger_client.rest import ApiException


class TestDevicegroupSchemaParagonactiveassurance(unittest.TestCase):
    """DevicegroupSchemaParagonactiveassurance unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDevicegroupSchemaParagonactiveassurance(self):
        """Test DevicegroupSchemaParagonactiveassurance"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.devicegroup_schema_paragonactiveassurance.DevicegroupSchemaParagonactiveassurance()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
